#! /bin/sh

# We need to make our own copy of the eclipse platform in order to
# build against it.  We do this since the build root might already
# contain a copy of the plugin we are building -- and the eclipse
# releng scripts fail in this situation.  We put this script in the
# eclipse core so that it is easy to use from other spec files.

# Arguments are:
# * directory where results should end up (script will make it)
# * base location of eclipse platform install
# * an optional string that is used to select non-platform
#   plugins and features.  At present if a plugin or feature has
#   this as a substring, it will be included.  You need only run
#   this script once, it will link both the platform and the other
#   optionally-selected parts in a single invocation.

# Test to see if the minimum arguments
# are specified

if [ $# -lt 2 ]; then
  echo "Usage: copy-platform where eclipse_base optional_directories"
  echo "For example: copy-plaform ~/SDK /usr/lib/eclipse cdt pydev jdt"
  exit 1
fi

where=$1; shift
eclipse=$1; shift

datadir=/usr/share/eclipse

mkdir -p $where/plugins $where/features
cd $where

# Are there any optional arguments left?
if [ $# -gt 0 ]; then
   for optional in "$@"; do
      (cd $eclipse;
	ls -d plugins/*"$optional"* features/*"$optional"* 2>/dev/null) |
      while read f; do
         [ ! -e $f ] && ln -s $eclipse/$f $f
      done
      (cd $eclipse/dropins; ls -d "$optional" 2>/dev/null) |
      while read f; do
	  if [ -e $eclipse/dropins/$f/eclipse ]; then
	      (cd $eclipse/dropins/$f/eclipse;
				ls -d plugins/* features/* 2>/dev/null) |
	      while read g; do
		  [ ! -e $g ] && \
		    ln -s $eclipse/dropins/$f/eclipse/$g $g
	      done
          else
	      (cd $eclipse/dropins/$f;
				ls -d plugins/* features/* 2>/dev/null) |
	      while read g; do
	          [ ! -e $g ] && \
		    ln -s $eclipse/dropins/$f/$g $g
	      done
          fi
      done
      (cd $datadir/dropins; ls -d "$optional" 2>/dev/null) |
      while read f; do
	  if [ -e $datadir/dropins/$f/eclipse ]; then
	      (cd $datadir/dropins/$f/eclipse;
				ls -d plugins/* features/* 2>/dev/null) |
	      while read g; do
		  [ ! -e $g ] && \
		    ln -s $datadir/dropins/$f/eclipse/$g $g
	      done
          else
	      (cd $datadir/dropins/$f;
				ls -d plugins/* features/* 2>/dev/null) |
	      while read g; do
	          [ ! -e $g ] && \
		    ln -s $datadir/dropins/$g $g
	      done
          fi
      done
   done
fi
for p in $(ls -d $eclipse/dropins/jdt/plugins/*); do
    plugin=$(basename $p)
    [ ! -e plugins/$plugin ] && ln -s $eclipse/dropins/jdt/plugins/$plugin plugins/$plugin
done
for f in $(ls -d $eclipse/dropins/jdt/features/*); do
    feature=$(basename $f)
    [ ! -e features/$feature ] && ln -s $eclipse/dropins/jdt/features/$feature features/$feature
done
for p in $(ls -d $eclipse/dropins/sdk/plugins/*); do
    plugin=$(basename $p)
    [ ! -e plugins/$plugin ] && ln -s $eclipse/dropins/sdk/plugins/$plugin plugins/$plugin
done
for f in $(ls -d $eclipse/dropins/sdk/features/*); do
    feature=$(basename $f)
    [ ! -e features/$feature ] && ln -s $eclipse/dropins/sdk/features/$feature features/$feature
done
for p in $(ls -d $eclipse/plugins/*); do
    plugin=$(basename $p)
    [ ! -e plugins/$plugin ] && ln -s $eclipse/plugins/$plugin plugins/$plugin
done
for f in $(ls -d $eclipse/features/*); do
    feature=$(basename $f)
    [ ! -e features/$feature ] && ln -s $eclipse/features/$feature features/$feature
done
[ ! -e artifacts.xml ] && ln -s $eclipse/artifacts.xml artifacts.xml
[ ! -e configuration ] && ln -s $eclipse/configuration configuration
[ ! -e eclipse ] && ln -s $eclipse/eclipse eclipse
[ ! -e eclipse.ini ] && ln -s $eclipse/eclipse.ini eclipse.ini
[ ! -e icon.xpm ] && ln -s $eclipse/icon.xpm icon.xpm
[ ! -e notice.html ] && ln -s $eclipse/notice.html notice.html
[ ! -e p2 ] && ln -s $eclipse/p2 p2
[ ! -e readme ] && ln -s $eclipse/readme readme
[ ! -e swt-gtk-3.8.1.jar ] && ln -s $eclipse/swt-gtk-3.8.1.jar swt-gtk-3.8.1.jar
[ ! -e swt-gtk.jar ] && ln -s $eclipse/swt-gtk.jar swt-gtk.jar
[ ! -e swt.jar ] && ln -s $eclipse/swt.jar swt.jar
[ ! -e artifacts.xml ] && ln -s $eclipse/artifacts.xml artifacts.xml
[ ! -e buildscripts ] && ln -s $eclipse/buildscripts buildscripts
[ ! -e configuration ] && ln -s $eclipse/configuration configuration
[ ! -e dropins ] && ln -s $eclipse/dropins dropins
[ ! -e eclipse ] && ln -s $eclipse/eclipse eclipse
[ ! -e eclipse.ini ] && ln -s $eclipse/eclipse.ini eclipse.ini
[ ! -e features ] && ln -s $eclipse/features features
[ ! -e features/org.eclipse.cvs_1.3.200.dist-7B79FJJ9exZ_ ] && ln -s $eclipse/features/org.eclipse.cvs_1.3.200.dist-7B79FJJ9exZ_ features/org.eclipse.cvs_1.3.200.dist-7B79FJJ9exZ_
[ ! -e features/org.eclipse.equinox.p2.core.feature_1.1.0.dist-829EFnfFKlR6A96 ] && ln -s $eclipse/features/org.eclipse.equinox.p2.core.feature_1.1.0.dist-829EFnfFKlR6A96 features/org.eclipse.equinox.p2.core.feature_1.1.0.dist-829EFnfFKlR6A96
[ ! -e features/org.eclipse.equinox.p2.extras.feature_1.1.0.dist-7A6FEcBpDPVGogGLmS7BA7 ] && ln -s $eclipse/features/org.eclipse.equinox.p2.extras.feature_1.1.0.dist-7A6FEcBpDPVGogGLmS7BA7 features/org.eclipse.equinox.p2.extras.feature_1.1.0.dist-7A6FEcBpDPVGogGLmS7BA7
[ ! -e features/org.eclipse.equinox.p2.rcp.feature_1.1.0.dist-785EoAUkciGogGLmS7BA7 ] && ln -s $eclipse/features/org.eclipse.equinox.p2.rcp.feature_1.1.0.dist-785EoAUkciGogGLmS7BA7 features/org.eclipse.equinox.p2.rcp.feature_1.1.0.dist-785EoAUkciGogGLmS7BA7
[ ! -e features/org.eclipse.equinox.p2.user.ui_2.2.0.dist-62DG8ltBZLdOsDwFEi8m9FbLOK8 ] && ln -s $eclipse/features/org.eclipse.equinox.p2.user.ui_2.2.0.dist-62DG8ltBZLdOsDwFEi8m9FbLOK8 features/org.eclipse.equinox.p2.user.ui_2.2.0.dist-62DG8ltBZLdOsDwFEi8m9FbLOK8
[ ! -e features/org.eclipse.help_1.4.1.dist-8v7nFQYFCmSPZXHoT2597H ] && ln -s $eclipse/features/org.eclipse.help_1.4.1.dist-8v7nFQYFCmSPZXHoT2597H features/org.eclipse.help_1.4.1.dist-8v7nFQYFCmSPZXHoT2597H
[ ! -e features/org.eclipse.platform_3.8.1.dist-A8F8_IVRG4VZSCmeloKVfCrtIFotGyJZcMPL9 ] && ln -s $eclipse/features/org.eclipse.platform_3.8.1.dist-A8F8_IVRG4VZSCmeloKVfCrtIFotGyJZcMPL9 features/org.eclipse.platform_3.8.1.dist-A8F8_IVRG4VZSCmeloKVfCrtIFotGyJZcMPL9
[ ! -e features/org.eclipse.rcp_3.8.1.dist-8LA2GODFTJUDJ21934 ] && ln -s $eclipse/features/org.eclipse.rcp_3.8.1.dist-8LA2GODFTJUDJ21934 features/org.eclipse.rcp_3.8.1.dist-8LA2GODFTJUDJ21934
[ ! -e icon.xpm ] && ln -s $eclipse/icon.xpm icon.xpm
[ ! -e notice.html ] && ln -s $eclipse/notice.html notice.html
[ ! -e p2 ] && ln -s $eclipse/p2 p2
[ ! -e plugins ] && ln -s $eclipse/plugins plugins
[ ! -e plugins/com.ibm.icu_4.4.2.v20110823.jar ] && ln -s $eclipse/plugins/com.ibm.icu_4.4.2.v20110823.jar plugins/com.ibm.icu_4.4.2.v20110823.jar
[ ! -e plugins/com.jcraft.jsch_0.1.50.jar ] && ln -s $eclipse/plugins/com.jcraft.jsch_0.1.50.jar plugins/com.jcraft.jsch_0.1.50.jar
[ ! -e plugins/javax.el_2.2.0.jar ] && ln -s $eclipse/plugins/javax.el_2.2.0.jar plugins/javax.el_2.2.0.jar
[ ! -e plugins/javax.servlet.jsp_2.2.0.v201103241327.jar ] && ln -s $eclipse/plugins/javax.servlet.jsp_2.2.0.v201103241327.jar plugins/javax.servlet.jsp_2.2.0.v201103241327.jar
[ ! -e plugins/javax.servlet_3.0.0.v201103241327.jar ] && ln -s $eclipse/plugins/javax.servlet_3.0.0.v201103241327.jar plugins/javax.servlet_3.0.0.v201103241327.jar
[ ! -e plugins/org.apache.ant_1.8.3.v20120321-1730 ] && ln -s $eclipse/plugins/org.apache.ant_1.8.3.v20120321-1730 plugins/org.apache.ant_1.8.3.v20120321-1730
[ ! -e plugins/org.apache.commons.codec_1.9.0.jar ] && ln -s $eclipse/plugins/org.apache.commons.codec_1.9.0.jar plugins/org.apache.commons.codec_1.9.0.jar
[ ! -e plugins/org.apache.commons.httpclient_3.1.0.jar ] && ln -s $eclipse/plugins/org.apache.commons.httpclient_3.1.0.jar plugins/org.apache.commons.httpclient_3.1.0.jar
[ ! -e plugins/org.apache.commons.logging_1.1.3.jar ] && ln -s $eclipse/plugins/org.apache.commons.logging_1.1.3.jar plugins/org.apache.commons.logging_1.1.3.jar
[ ! -e plugins/org.apache.el_7.0.26.jar ] && ln -s $eclipse/plugins/org.apache.el_7.0.26.jar plugins/org.apache.el_7.0.26.jar
[ ! -e plugins/org.apache.felix.gogo.command_0.12.0.jar ] && ln -s $eclipse/plugins/org.apache.felix.gogo.command_0.12.0.jar plugins/org.apache.felix.gogo.command_0.12.0.jar
[ ! -e plugins/org.apache.felix.gogo.runtime_0.10.0.jar ] && ln -s $eclipse/plugins/org.apache.felix.gogo.runtime_0.10.0.jar plugins/org.apache.felix.gogo.runtime_0.10.0.jar
[ ! -e plugins/org.apache.felix.gogo.shell_0.10.0.jar ] && ln -s $eclipse/plugins/org.apache.felix.gogo.shell_0.10.0.jar plugins/org.apache.felix.gogo.shell_0.10.0.jar
[ ! -e plugins/org.apache.jasper_7.0.26.jar ] && ln -s $eclipse/plugins/org.apache.jasper_7.0.26.jar plugins/org.apache.jasper_7.0.26.jar
[ ! -e plugins/org.apache.juli_7.0.26.jar ] && ln -s $eclipse/plugins/org.apache.juli_7.0.26.jar plugins/org.apache.juli_7.0.26.jar
[ ! -e plugins/org.apache.lucene.analysis_2.9.4.jar ] && ln -s $eclipse/plugins/org.apache.lucene.analysis_2.9.4.jar plugins/org.apache.lucene.analysis_2.9.4.jar
[ ! -e plugins/org.apache.lucene.core_2.9.4.jar ] && ln -s $eclipse/plugins/org.apache.lucene.core_2.9.4.jar plugins/org.apache.lucene.core_2.9.4.jar
[ ! -e plugins/org.apache.tomcat.api_7.0.26.jar ] && ln -s $eclipse/plugins/org.apache.tomcat.api_7.0.26.jar plugins/org.apache.tomcat.api_7.0.26.jar
[ ! -e plugins/org.apache.tomcat.util_7.0.26.jar ] && ln -s $eclipse/plugins/org.apache.tomcat.util_7.0.26.jar plugins/org.apache.tomcat.util_7.0.26.jar
[ ! -e plugins/org.eclipse.ant.core_3.2.400.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ant.core_3.2.400.dist.jar plugins/org.eclipse.ant.core_3.2.400.dist.jar
[ ! -e plugins/org.eclipse.compare.core_3.5.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.compare.core_3.5.200.dist.jar plugins/org.eclipse.compare.core_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.compare_3.5.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.compare_3.5.300.dist.jar plugins/org.eclipse.compare_3.5.300.dist.jar
[ ! -e plugins/org.eclipse.core.boot_3.1.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.boot_3.1.300.dist.jar plugins/org.eclipse.core.boot_3.1.300.dist.jar
[ ! -e plugins/org.eclipse.core.commands_3.6.1.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.commands_3.6.1.dist.jar plugins/org.eclipse.core.commands_3.6.1.dist.jar
[ ! -e plugins/org.eclipse.core.contenttype_3.4.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.contenttype_3.4.200.dist.jar plugins/org.eclipse.core.contenttype_3.4.200.dist.jar
[ ! -e plugins/org.eclipse.core.databinding.beans_1.2.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.databinding.beans_1.2.200.dist.jar plugins/org.eclipse.core.databinding.beans_1.2.200.dist.jar
[ ! -e plugins/org.eclipse.core.databinding.observable_1.4.1.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.databinding.observable_1.4.1.dist.jar plugins/org.eclipse.core.databinding.observable_1.4.1.dist.jar
[ ! -e plugins/org.eclipse.core.databinding.property_1.4.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.databinding.property_1.4.100.dist.jar plugins/org.eclipse.core.databinding.property_1.4.100.dist.jar
[ ! -e plugins/org.eclipse.core.databinding_1.4.1.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.databinding_1.4.1.dist.jar plugins/org.eclipse.core.databinding_1.4.1.dist.jar
[ ! -e plugins/org.eclipse.core.expressions_3.4.400.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.expressions_3.4.400.dist.jar plugins/org.eclipse.core.expressions_3.4.400.dist.jar
[ ! -e plugins/org.eclipse.core.externaltools_1.0.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.externaltools_1.0.100.dist.jar plugins/org.eclipse.core.externaltools_1.0.100.dist.jar
[ ! -e plugins/org.eclipse.core.filebuffers_3.5.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.filebuffers_3.5.200.dist.jar plugins/org.eclipse.core.filebuffers_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.core.filesystem.linux.x86_64_1.2.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.filesystem.linux.x86_64_1.2.0.dist.jar plugins/org.eclipse.core.filesystem.linux.x86_64_1.2.0.dist.jar
[ ! -e plugins/org.eclipse.core.filesystem_1.3.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.filesystem_1.3.200.dist.jar plugins/org.eclipse.core.filesystem_1.3.200.dist.jar
[ ! -e plugins/org.eclipse.core.jobs_3.5.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.jobs_3.5.200.dist.jar plugins/org.eclipse.core.jobs_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.core.net.linux.x86_64_1.1.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.net.linux.x86_64_1.1.0.dist.jar plugins/org.eclipse.core.net.linux.x86_64_1.1.0.dist.jar
[ ! -e plugins/org.eclipse.core.net_1.2.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.net_1.2.200.dist.jar plugins/org.eclipse.core.net_1.2.200.dist.jar
[ ! -e plugins/org.eclipse.core.resources_3.8.1.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.resources_3.8.1.dist.jar plugins/org.eclipse.core.resources_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.core.runtime.compatibility.auth_3.2.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.runtime.compatibility.auth_3.2.300.dist.jar plugins/org.eclipse.core.runtime.compatibility.auth_3.2.300.dist.jar
[ ! -e plugins/org.eclipse.core.runtime.compatibility.registry_3.5.100.dist ] && ln -s $eclipse/plugins/org.eclipse.core.runtime.compatibility.registry_3.5.100.dist plugins/org.eclipse.core.runtime.compatibility.registry_3.5.100.dist
[ ! -e plugins/org.eclipse.core.runtime.compatibility_3.2.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.runtime.compatibility_3.2.200.dist.jar plugins/org.eclipse.core.runtime.compatibility_3.2.200.dist.jar
[ ! -e plugins/org.eclipse.core.runtime_3.8.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.runtime_3.8.0.dist.jar plugins/org.eclipse.core.runtime_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.core.variables_3.2.600.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.core.variables_3.2.600.dist.jar plugins/org.eclipse.core.variables_3.2.600.dist.jar
[ ! -e plugins/org.eclipse.cvs_1.2.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.cvs_1.2.0.dist.jar plugins/org.eclipse.cvs_1.2.0.dist.jar
[ ! -e plugins/org.eclipse.debug.core_3.7.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.debug.core_3.7.100.dist.jar plugins/org.eclipse.debug.core_3.7.100.dist.jar
[ ! -e plugins/org.eclipse.debug.ui_3.8.1.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.debug.ui_3.8.1.dist.jar plugins/org.eclipse.debug.ui_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.ecf.filetransfer_5.0.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ecf.filetransfer_5.0.0.dist.jar plugins/org.eclipse.ecf.filetransfer_5.0.0.dist.jar
[ ! -e plugins/org.eclipse.ecf.identity_3.1.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ecf.identity_3.1.200.dist.jar plugins/org.eclipse.ecf.identity_3.1.200.dist.jar
[ ! -e plugins/org.eclipse.ecf.provider.filetransfer.httpclient.ssl_1.0.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ecf.provider.filetransfer.httpclient.ssl_1.0.0.dist.jar plugins/org.eclipse.ecf.provider.filetransfer.httpclient.ssl_1.0.0.dist.jar
[ ! -e plugins/org.eclipse.ecf.provider.filetransfer.httpclient_4.0.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ecf.provider.filetransfer.httpclient_4.0.200.dist.jar plugins/org.eclipse.ecf.provider.filetransfer.httpclient_4.0.200.dist.jar
[ ! -e plugins/org.eclipse.ecf.provider.filetransfer.ssl_1.0.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ecf.provider.filetransfer.ssl_1.0.0.dist.jar plugins/org.eclipse.ecf.provider.filetransfer.ssl_1.0.0.dist.jar
[ ! -e plugins/org.eclipse.ecf.provider.filetransfer_3.2.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ecf.provider.filetransfer_3.2.0.dist.jar plugins/org.eclipse.ecf.provider.filetransfer_3.2.0.dist.jar
[ ! -e plugins/org.eclipse.ecf.ssl_1.0.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ecf.ssl_1.0.100.dist.jar plugins/org.eclipse.ecf.ssl_1.0.100.dist.jar
[ ! -e plugins/org.eclipse.ecf_3.1.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ecf_3.1.300.dist.jar plugins/org.eclipse.ecf_3.1.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.app_1.3.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.app_1.3.100.dist.jar plugins/org.eclipse.equinox.app_1.3.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.bidi_0.9.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.bidi_0.9.0.dist.jar plugins/org.eclipse.equinox.bidi_0.9.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.common_3.6.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.common_3.6.100.dist.jar plugins/org.eclipse.equinox.common_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.concurrent_1.0.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.concurrent_1.0.300.dist.jar plugins/org.eclipse.equinox.concurrent_1.0.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.console_1.0.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.console_1.0.0.dist.jar plugins/org.eclipse.equinox.console_1.0.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.ds_1.4.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.ds_1.4.0.dist.jar plugins/org.eclipse.equinox.ds_1.4.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.event_1.2.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.event_1.2.200.dist.jar plugins/org.eclipse.equinox.event_1.2.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.frameworkadmin.equinox_1.0.400.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.frameworkadmin.equinox_1.0.400.dist.jar plugins/org.eclipse.equinox.frameworkadmin.equinox_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.equinox.frameworkadmin_2.0.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.frameworkadmin_2.0.100.dist.jar plugins/org.eclipse.equinox.frameworkadmin_2.0.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.http.jetty_3.0.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.http.jetty_3.0.0.dist.jar plugins/org.eclipse.equinox.http.jetty_3.0.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.http.registry_1.1.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.http.registry_1.1.200.dist.jar plugins/org.eclipse.equinox.http.registry_1.1.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.http.servlet_1.1.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.http.servlet_1.1.300.dist.jar plugins/org.eclipse.equinox.http.servlet_1.1.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.initializer_1.0.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.initializer_1.0.0.dist.jar plugins/org.eclipse.equinox.initializer_1.0.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.jsp.jasper.registry_1.0.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.jsp.jasper.registry_1.0.300.dist.jar plugins/org.eclipse.equinox.jsp.jasper.registry_1.0.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.jsp.jasper_1.0.400.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.jsp.jasper_1.0.400.dist.jar plugins/org.eclipse.equinox.jsp.jasper_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.200.dist ] && ln -s $eclipse/plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.200.dist plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.200.dist
[ ! -e plugins/org.eclipse.equinox.launcher_1.3.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.launcher_1.3.0.dist.jar plugins/org.eclipse.equinox.launcher_1.3.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.log_1.2.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.log_1.2.300.dist.jar plugins/org.eclipse.equinox.log_1.2.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.artifact.repository_1.1.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.artifact.repository_1.1.200.dist.jar plugins/org.eclipse.equinox.p2.artifact.repository_1.1.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.console_1.0.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.console_1.0.300.dist.jar plugins/org.eclipse.equinox.p2.console_1.0.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.core_2.2.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.core_2.2.0.dist.jar plugins/org.eclipse.equinox.p2.core_2.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.director.app_1.0.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.director.app_1.0.300.dist.jar plugins/org.eclipse.equinox.p2.director.app_1.0.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.director_2.2.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.director_2.2.0.dist.jar plugins/org.eclipse.equinox.p2.director_2.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.directorywatcher_1.0.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.directorywatcher_1.0.300.dist.jar plugins/org.eclipse.equinox.p2.directorywatcher_1.0.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.engine_2.2.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.engine_2.2.0.dist.jar plugins/org.eclipse.equinox.p2.engine_2.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.extensionlocation_1.2.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.extensionlocation_1.2.100.dist.jar plugins/org.eclipse.equinox.p2.extensionlocation_1.2.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.garbagecollector_1.0.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.garbagecollector_1.0.200.dist.jar plugins/org.eclipse.equinox.p2.garbagecollector_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.jarprocessor_1.0.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.jarprocessor_1.0.200.dist.jar plugins/org.eclipse.equinox.p2.jarprocessor_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.metadata.repository_1.2.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.metadata.repository_1.2.100.dist.jar plugins/org.eclipse.equinox.p2.metadata.repository_1.2.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.metadata_2.1.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.metadata_2.1.0.dist.jar plugins/org.eclipse.equinox.p2.metadata_2.1.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.operations_2.2.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.operations_2.2.0.dist.jar plugins/org.eclipse.equinox.p2.operations_2.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.publisher.eclipse_1.1.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.publisher.eclipse_1.1.0.dist.jar plugins/org.eclipse.equinox.p2.publisher.eclipse_1.1.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.publisher_1.2.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.publisher_1.2.0.dist.jar plugins/org.eclipse.equinox.p2.publisher_1.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.ql_2.0.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.ql_2.0.100.dist.jar plugins/org.eclipse.equinox.p2.ql_2.0.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.reconciler.dropins_1.1.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.reconciler.dropins_1.1.200.dist.jar plugins/org.eclipse.equinox.p2.reconciler.dropins_1.1.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.repository.tools_2.0.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.repository.tools_2.0.100.dist.jar plugins/org.eclipse.equinox.p2.repository.tools_2.0.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.repository_2.2.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.repository_2.2.0.dist.jar plugins/org.eclipse.equinox.p2.repository_2.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.touchpoint.eclipse_2.1.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.touchpoint.eclipse_2.1.100.dist.jar plugins/org.eclipse.equinox.p2.touchpoint.eclipse_2.1.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.touchpoint.natives_1.1.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.touchpoint.natives_1.1.0.dist.jar plugins/org.eclipse.equinox.p2.touchpoint.natives_1.1.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.transport.ecf_1.0.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.transport.ecf_1.0.100.dist.jar plugins/org.eclipse.equinox.p2.transport.ecf_1.0.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.ui.importexport_1.0.1.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.ui.importexport_1.0.1.dist.jar plugins/org.eclipse.equinox.p2.ui.importexport_1.0.1.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.ui.sdk.scheduler_1.1.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.ui.sdk.scheduler_1.1.0.dist.jar plugins/org.eclipse.equinox.p2.ui.sdk.scheduler_1.1.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.ui.sdk_1.0.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.ui.sdk_1.0.200.dist.jar plugins/org.eclipse.equinox.p2.ui.sdk_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.ui_2.2.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.ui_2.2.0.dist.jar plugins/org.eclipse.equinox.p2.ui_2.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.updatechecker_1.1.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.updatechecker_1.1.200.dist.jar plugins/org.eclipse.equinox.p2.updatechecker_1.1.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.updatesite_1.0.400.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.p2.updatesite_1.0.400.dist.jar plugins/org.eclipse.equinox.p2.updatesite_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.equinox.preferences_3.5.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.preferences_3.5.0.dist.jar plugins/org.eclipse.equinox.preferences_3.5.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.registry_3.5.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.registry_3.5.200.dist.jar plugins/org.eclipse.equinox.registry_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.security.ui_1.1.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.security.ui_1.1.100.dist.jar plugins/org.eclipse.equinox.security.ui_1.1.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.security_1.1.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.security_1.1.100.dist.jar plugins/org.eclipse.equinox.security_1.1.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.simpleconfigurator.manipulator_2.0.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.simpleconfigurator.manipulator_2.0.0.dist.jar plugins/org.eclipse.equinox.simpleconfigurator.manipulator_2.0.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.simpleconfigurator_1.0.301.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.simpleconfigurator_1.0.301.dist.jar plugins/org.eclipse.equinox.simpleconfigurator_1.0.301.dist.jar
[ ! -e plugins/org.eclipse.equinox.util_1.0.400.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.equinox.util_1.0.400.dist.jar plugins/org.eclipse.equinox.util_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.help.appserver_3.1.400.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.help.appserver_3.1.400.dist.jar plugins/org.eclipse.help.appserver_3.1.400.dist.jar
[ ! -e plugins/org.eclipse.help.base_3.6.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.help.base_3.6.100.dist.jar plugins/org.eclipse.help.base_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.help.ui_3.5.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.help.ui_3.5.200.dist.jar plugins/org.eclipse.help.ui_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.help.webapp_3.6.101.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.help.webapp_3.6.101.dist.jar plugins/org.eclipse.help.webapp_3.6.101.dist.jar
[ ! -e plugins/org.eclipse.help_3.6.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.help_3.6.0.dist.jar plugins/org.eclipse.help_3.6.0.dist.jar
[ ! -e plugins/org.eclipse.jdt.core_3.8.2.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.jdt.core_3.8.2.dist.jar plugins/org.eclipse.jdt.core_3.8.2.dist.jar
[ ! -e plugins/org.eclipse.jetty.continuation_8.1.3.v20120416.jar ] && ln -s $eclipse/plugins/org.eclipse.jetty.continuation_8.1.3.v20120416.jar plugins/org.eclipse.jetty.continuation_8.1.3.v20120416.jar
[ ! -e plugins/org.eclipse.jetty.http_8.1.3.v20120416.jar ] && ln -s $eclipse/plugins/org.eclipse.jetty.http_8.1.3.v20120416.jar plugins/org.eclipse.jetty.http_8.1.3.v20120416.jar
[ ! -e plugins/org.eclipse.jetty.io_8.1.3.v20120416.jar ] && ln -s $eclipse/plugins/org.eclipse.jetty.io_8.1.3.v20120416.jar plugins/org.eclipse.jetty.io_8.1.3.v20120416.jar
[ ! -e plugins/org.eclipse.jetty.security_8.1.3.v20120416.jar ] && ln -s $eclipse/plugins/org.eclipse.jetty.security_8.1.3.v20120416.jar plugins/org.eclipse.jetty.security_8.1.3.v20120416.jar
[ ! -e plugins/org.eclipse.jetty.server_8.1.3.v20120416.jar ] && ln -s $eclipse/plugins/org.eclipse.jetty.server_8.1.3.v20120416.jar plugins/org.eclipse.jetty.server_8.1.3.v20120416.jar
[ ! -e plugins/org.eclipse.jetty.servlet_8.1.3.v20120416.jar ] && ln -s $eclipse/plugins/org.eclipse.jetty.servlet_8.1.3.v20120416.jar plugins/org.eclipse.jetty.servlet_8.1.3.v20120416.jar
[ ! -e plugins/org.eclipse.jetty.util_8.1.3.v20120416.jar ] && ln -s $eclipse/plugins/org.eclipse.jetty.util_8.1.3.v20120416.jar plugins/org.eclipse.jetty.util_8.1.3.v20120416.jar
[ ! -e plugins/org.eclipse.jface.databinding_1.6.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.jface.databinding_1.6.0.dist.jar plugins/org.eclipse.jface.databinding_1.6.0.dist.jar
[ ! -e plugins/org.eclipse.jface.text_3.8.1.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.jface.text_3.8.1.dist.jar plugins/org.eclipse.jface.text_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.jface_3.8.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.jface_3.8.0.dist.jar plugins/org.eclipse.jface_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.jsch.core_1.1.400.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.jsch.core_1.1.400.dist.jar plugins/org.eclipse.jsch.core_1.1.400.dist.jar
[ ! -e plugins/org.eclipse.jsch.ui_1.1.400.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.jsch.ui_1.1.400.dist.jar plugins/org.eclipse.jsch.ui_1.1.400.dist.jar
[ ! -e plugins/org.eclipse.ltk.core.refactoring_3.6.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ltk.core.refactoring_3.6.0.dist.jar plugins/org.eclipse.ltk.core.refactoring_3.6.0.dist.jar
[ ! -e plugins/org.eclipse.ltk.ui.refactoring_3.7.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ltk.ui.refactoring_3.7.0.dist.jar plugins/org.eclipse.ltk.ui.refactoring_3.7.0.dist.jar
[ ! -e plugins/org.eclipse.osgi.services_3.3.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.osgi.services_3.3.100.dist.jar plugins/org.eclipse.osgi.services_3.3.100.dist.jar
[ ! -e plugins/org.eclipse.osgi.util_3.2.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.osgi.util_3.2.300.dist.jar plugins/org.eclipse.osgi.util_3.2.300.dist.jar
[ ! -e plugins/org.eclipse.osgi_3.8.1.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.osgi_3.8.1.dist.jar plugins/org.eclipse.osgi_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.platform.doc.user_3.8.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.platform.doc.user_3.8.0.dist.jar plugins/org.eclipse.platform.doc.user_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.platform_3.8.1.dist ] && ln -s $eclipse/plugins/org.eclipse.platform_3.8.1.dist plugins/org.eclipse.platform_3.8.1.dist
[ ! -e plugins/org.eclipse.rcp_3.8.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.rcp_3.8.0.dist.jar plugins/org.eclipse.rcp_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.search_3.8.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.search_3.8.0.dist.jar plugins/org.eclipse.search_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.swt_3.8.2.jar ] && ln -s $eclipse/plugins/org.eclipse.swt_3.8.2.jar plugins/org.eclipse.swt_3.8.2.jar
[ ! -e plugins/org.eclipse.team.core_3.6.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.team.core_3.6.100.dist.jar plugins/org.eclipse.team.core_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.team.cvs.core_3.3.500.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.team.cvs.core_3.3.500.dist.jar plugins/org.eclipse.team.cvs.core_3.3.500.dist.jar
[ ! -e plugins/org.eclipse.team.cvs.ssh2_3.2.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.team.cvs.ssh2_3.2.300.dist.jar plugins/org.eclipse.team.cvs.ssh2_3.2.300.dist.jar
[ ! -e plugins/org.eclipse.team.cvs.ui_3.3.500.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.team.cvs.ui_3.3.500.dist.jar plugins/org.eclipse.team.cvs.ui_3.3.500.dist.jar
[ ! -e plugins/org.eclipse.team.ui_3.6.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.team.ui_3.6.200.dist.jar plugins/org.eclipse.team.ui_3.6.200.dist.jar
[ ! -e plugins/org.eclipse.text_3.5.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.text_3.5.200.dist.jar plugins/org.eclipse.text_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.ui.browser_3.4.1.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.browser_3.4.1.dist.jar plugins/org.eclipse.ui.browser_3.4.1.dist.jar
[ ! -e plugins/org.eclipse.ui.cheatsheets_3.4.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.cheatsheets_3.4.200.dist.jar plugins/org.eclipse.ui.cheatsheets_3.4.200.dist.jar
[ ! -e plugins/org.eclipse.ui.console_3.5.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.console_3.5.100.dist.jar plugins/org.eclipse.ui.console_3.5.100.dist.jar
[ ! -e plugins/org.eclipse.ui.editors_3.8.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.editors_3.8.0.dist.jar plugins/org.eclipse.ui.editors_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.ui.externaltools_3.2.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.externaltools_3.2.100.dist.jar plugins/org.eclipse.ui.externaltools_3.2.100.dist.jar
[ ! -e plugins/org.eclipse.ui.forms_3.5.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.forms_3.5.200.dist.jar plugins/org.eclipse.ui.forms_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.ui.ide.application_1.0.400.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.ide.application_1.0.400.dist.jar plugins/org.eclipse.ui.ide.application_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.ui.ide_3.8.1.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.ide_3.8.1.dist.jar plugins/org.eclipse.ui.ide_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.ui.intro.universal_3.2.600.dist ] && ln -s $eclipse/plugins/org.eclipse.ui.intro.universal_3.2.600.dist plugins/org.eclipse.ui.intro.universal_3.2.600.dist
[ ! -e plugins/org.eclipse.ui.intro_3.4.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.intro_3.4.200.dist.jar plugins/org.eclipse.ui.intro_3.4.200.dist.jar
[ ! -e plugins/org.eclipse.ui.navigator.resources_3.4.400.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.navigator.resources_3.4.400.dist.jar plugins/org.eclipse.ui.navigator.resources_3.4.400.dist.jar
[ ! -e plugins/org.eclipse.ui.navigator_3.5.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.navigator_3.5.200.dist.jar plugins/org.eclipse.ui.navigator_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.ui.net_1.2.101.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.net_1.2.101.dist.jar plugins/org.eclipse.ui.net_1.2.101.dist.jar
[ ! -e plugins/org.eclipse.ui.presentations.r21_3.2.201.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.presentations.r21_3.2.201.dist.jar plugins/org.eclipse.ui.presentations.r21_3.2.201.dist.jar
[ ! -e plugins/org.eclipse.ui.views.properties.tabbed_3.5.300.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.views.properties.tabbed_3.5.300.dist.jar plugins/org.eclipse.ui.views.properties.tabbed_3.5.300.dist.jar
[ ! -e plugins/org.eclipse.ui.views_3.6.100.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.views_3.6.100.dist.jar plugins/org.eclipse.ui.views_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.ui.workbench.compatibility_3.2.101.dist ] && ln -s $eclipse/plugins/org.eclipse.ui.workbench.compatibility_3.2.101.dist plugins/org.eclipse.ui.workbench.compatibility_3.2.101.dist
[ ! -e plugins/org.eclipse.ui.workbench.texteditor_3.8.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.workbench.texteditor_3.8.0.dist.jar plugins/org.eclipse.ui.workbench.texteditor_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.ui.workbench_3.8.1.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui.workbench_3.8.1.dist.jar plugins/org.eclipse.ui.workbench_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.ui_3.8.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.ui_3.8.0.dist.jar plugins/org.eclipse.ui_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.update.configurator_3.3.200.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.update.configurator_3.3.200.dist.jar plugins/org.eclipse.update.configurator_3.3.200.dist.jar
[ ! -e plugins/org.eclipse.update.core_3.2.600.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.update.core_3.2.600.dist.jar plugins/org.eclipse.update.core_3.2.600.dist.jar
[ ! -e plugins/org.eclipse.update.scheduler_3.2.400.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.update.scheduler_3.2.400.dist.jar plugins/org.eclipse.update.scheduler_3.2.400.dist.jar
[ ! -e plugins/org.eclipse.update.ui_3.3.0.dist.jar ] && ln -s $eclipse/plugins/org.eclipse.update.ui_3.3.0.dist.jar plugins/org.eclipse.update.ui_3.3.0.dist.jar
[ ! -e plugins/org.sat4j.core_2.3.2.WHEEZY.jar ] && ln -s $eclipse/plugins/org.sat4j.core_2.3.2.WHEEZY.jar plugins/org.sat4j.core_2.3.2.WHEEZY.jar
[ ! -e plugins/org.sat4j.pb_2.3.2.WHEEZY.jar ] && ln -s $eclipse/plugins/org.sat4j.pb_2.3.2.WHEEZY.jar plugins/org.sat4j.pb_2.3.2.WHEEZY.jar
[ ! -e readme ] && ln -s $eclipse/readme readme
[ ! -e swt-gtk-3.8.1.jar ] && ln -s $eclipse/swt-gtk-3.8.1.jar swt-gtk-3.8.1.jar
[ ! -e swt-gtk.jar ] && ln -s $eclipse/swt-gtk.jar swt-gtk.jar
[ ! -e swt.jar ] && ln -s $eclipse/swt.jar swt.jar
[ ! -e plugins/org.apache.ant.source_1.8.3.v20120321-1730.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.apache.ant.source_1.8.3.v20120321-1730.jar plugins/org.apache.ant.source_1.8.3.v20120321-1730.jar
[ ! -e plugins/org.eclipse.ant.core.source_3.2.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ant.core.source_3.2.400.dist.jar plugins/org.eclipse.ant.core.source_3.2.400.dist.jar
[ ! -e plugins/org.eclipse.ant.launching.source_1.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ant.launching.source_1.0.200.dist.jar plugins/org.eclipse.ant.launching.source_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.ant.ui.source_3.5.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ant.ui.source_3.5.300.dist.jar plugins/org.eclipse.ant.ui.source_3.5.300.dist.jar
[ ! -e plugins/org.eclipse.compare.core.source_3.5.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.compare.core.source_3.5.200.dist.jar plugins/org.eclipse.compare.core.source_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.compare.source_3.5.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.compare.source_3.5.300.dist.jar plugins/org.eclipse.compare.source_3.5.300.dist.jar
[ ! -e plugins/org.eclipse.core.commands.source_3.6.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.commands.source_3.6.1.dist.jar plugins/org.eclipse.core.commands.source_3.6.1.dist.jar
[ ! -e plugins/org.eclipse.core.contenttype.source_3.4.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.contenttype.source_3.4.200.dist.jar plugins/org.eclipse.core.contenttype.source_3.4.200.dist.jar
[ ! -e plugins/org.eclipse.core.databinding.beans.source_1.2.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.databinding.beans.source_1.2.200.dist.jar plugins/org.eclipse.core.databinding.beans.source_1.2.200.dist.jar
[ ! -e plugins/org.eclipse.core.databinding.observable.source_1.4.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.databinding.observable.source_1.4.1.dist.jar plugins/org.eclipse.core.databinding.observable.source_1.4.1.dist.jar
[ ! -e plugins/org.eclipse.core.databinding.property.source_1.4.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.databinding.property.source_1.4.100.dist.jar plugins/org.eclipse.core.databinding.property.source_1.4.100.dist.jar
[ ! -e plugins/org.eclipse.core.databinding.source_1.4.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.databinding.source_1.4.1.dist.jar plugins/org.eclipse.core.databinding.source_1.4.1.dist.jar
[ ! -e plugins/org.eclipse.core.expressions.source_3.4.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.expressions.source_3.4.400.dist.jar plugins/org.eclipse.core.expressions.source_3.4.400.dist.jar
[ ! -e plugins/org.eclipse.core.externaltools.source_1.0.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.externaltools.source_1.0.100.dist.jar plugins/org.eclipse.core.externaltools.source_1.0.100.dist.jar
[ ! -e plugins/org.eclipse.core.filebuffers.source_3.5.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.filebuffers.source_3.5.200.dist.jar plugins/org.eclipse.core.filebuffers.source_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.core.filesystem.source_1.3.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.filesystem.source_1.3.200.dist.jar plugins/org.eclipse.core.filesystem.source_1.3.200.dist.jar
[ ! -e plugins/org.eclipse.core.jobs.source_3.5.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.jobs.source_3.5.200.dist.jar plugins/org.eclipse.core.jobs.source_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.core.net.source_1.2.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.net.source_1.2.200.dist.jar plugins/org.eclipse.core.net.source_1.2.200.dist.jar
[ ! -e plugins/org.eclipse.core.resources.source_3.8.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.resources.source_3.8.1.dist.jar plugins/org.eclipse.core.resources.source_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.core.runtime.compatibility.auth.source_3.2.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.runtime.compatibility.auth.source_3.2.300.dist.jar plugins/org.eclipse.core.runtime.compatibility.auth.source_3.2.300.dist.jar
[ ! -e plugins/org.eclipse.core.runtime.compatibility.registry.source_3.5.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.runtime.compatibility.registry.source_3.5.100.dist.jar plugins/org.eclipse.core.runtime.compatibility.registry.source_3.5.100.dist.jar
[ ! -e plugins/org.eclipse.core.runtime.compatibility.source_3.2.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.runtime.compatibility.source_3.2.200.dist.jar plugins/org.eclipse.core.runtime.compatibility.source_3.2.200.dist.jar
[ ! -e plugins/org.eclipse.core.runtime.source_3.8.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.runtime.source_3.8.0.dist.jar plugins/org.eclipse.core.runtime.source_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.core.variables.source_3.2.600.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.core.variables.source_3.2.600.dist.jar plugins/org.eclipse.core.variables.source_3.2.600.dist.jar
[ ! -e plugins/org.eclipse.cvs.source_1.2.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.cvs.source_1.2.0.dist.jar plugins/org.eclipse.cvs.source_1.2.0.dist.jar
[ ! -e plugins/org.eclipse.debug.core.source_3.7.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.debug.core.source_3.7.100.dist.jar plugins/org.eclipse.debug.core.source_3.7.100.dist.jar
[ ! -e plugins/org.eclipse.debug.ui.source_3.8.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.debug.ui.source_3.8.1.dist.jar plugins/org.eclipse.debug.ui.source_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.ecf.filetransfer.source_5.0.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ecf.filetransfer.source_5.0.0.dist.jar plugins/org.eclipse.ecf.filetransfer.source_5.0.0.dist.jar
[ ! -e plugins/org.eclipse.ecf.identity.source_3.1.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ecf.identity.source_3.1.200.dist.jar plugins/org.eclipse.ecf.identity.source_3.1.200.dist.jar
[ ! -e plugins/org.eclipse.ecf.provider.filetransfer.httpclient.source_4.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ecf.provider.filetransfer.httpclient.source_4.0.200.dist.jar plugins/org.eclipse.ecf.provider.filetransfer.httpclient.source_4.0.200.dist.jar
[ ! -e plugins/org.eclipse.ecf.provider.filetransfer.httpclient.ssl.source_1.0.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ecf.provider.filetransfer.httpclient.ssl.source_1.0.0.dist.jar plugins/org.eclipse.ecf.provider.filetransfer.httpclient.ssl.source_1.0.0.dist.jar
[ ! -e plugins/org.eclipse.ecf.provider.filetransfer.source_3.2.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ecf.provider.filetransfer.source_3.2.0.dist.jar plugins/org.eclipse.ecf.provider.filetransfer.source_3.2.0.dist.jar
[ ! -e plugins/org.eclipse.ecf.provider.filetransfer.ssl.source_1.0.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ecf.provider.filetransfer.ssl.source_1.0.0.dist.jar plugins/org.eclipse.ecf.provider.filetransfer.ssl.source_1.0.0.dist.jar
[ ! -e plugins/org.eclipse.ecf.source_3.1.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ecf.source_3.1.300.dist.jar plugins/org.eclipse.ecf.source_3.1.300.dist.jar
[ ! -e plugins/org.eclipse.ecf.ssl.source_1.0.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ecf.ssl.source_1.0.100.dist.jar plugins/org.eclipse.ecf.ssl.source_1.0.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.app.source_1.3.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.app.source_1.3.100.dist.jar plugins/org.eclipse.equinox.app.source_1.3.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.bidi.source_0.9.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.bidi.source_0.9.0.dist.jar plugins/org.eclipse.equinox.bidi.source_0.9.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.common.source_3.6.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.common.source_3.6.100.dist.jar plugins/org.eclipse.equinox.common.source_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.concurrent.source_1.0.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.concurrent.source_1.0.300.dist.jar plugins/org.eclipse.equinox.concurrent.source_1.0.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.console.source_1.0.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.console.source_1.0.0.dist.jar plugins/org.eclipse.equinox.console.source_1.0.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.ds.source_1.4.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.ds.source_1.4.0.dist.jar plugins/org.eclipse.equinox.ds.source_1.4.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.event.source_1.2.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.event.source_1.2.200.dist.jar plugins/org.eclipse.equinox.event.source_1.2.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.frameworkadmin.equinox.source_1.0.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.frameworkadmin.equinox.source_1.0.400.dist.jar plugins/org.eclipse.equinox.frameworkadmin.equinox.source_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.equinox.frameworkadmin.source_2.0.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.frameworkadmin.source_2.0.100.dist.jar plugins/org.eclipse.equinox.frameworkadmin.source_2.0.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.http.jetty.source_3.0.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.http.jetty.source_3.0.0.dist.jar plugins/org.eclipse.equinox.http.jetty.source_3.0.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.http.registry.source_1.1.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.http.registry.source_1.1.200.dist.jar plugins/org.eclipse.equinox.http.registry.source_1.1.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.http.servlet.source_1.1.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.http.servlet.source_1.1.300.dist.jar plugins/org.eclipse.equinox.http.servlet.source_1.1.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.jsp.jasper.registry.source_1.0.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.jsp.jasper.registry.source_1.0.300.dist.jar plugins/org.eclipse.equinox.jsp.jasper.registry.source_1.0.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.jsp.jasper.source_1.0.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.jsp.jasper.source_1.0.400.dist.jar plugins/org.eclipse.equinox.jsp.jasper.source_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.equinox.launcher.source_1.3.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.launcher.source_1.3.0.dist.jar plugins/org.eclipse.equinox.launcher.source_1.3.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.log.source_1.2.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.log.source_1.2.300.dist.jar plugins/org.eclipse.equinox.log.source_1.2.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.artifact.repository.source_1.1.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.artifact.repository.source_1.1.200.dist.jar plugins/org.eclipse.equinox.p2.artifact.repository.source_1.1.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.console.source_1.0.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.console.source_1.0.300.dist.jar plugins/org.eclipse.equinox.p2.console.source_1.0.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.core.source_2.2.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.core.source_2.2.0.dist.jar plugins/org.eclipse.equinox.p2.core.source_2.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.director.app.source_1.0.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.director.app.source_1.0.300.dist.jar plugins/org.eclipse.equinox.p2.director.app.source_1.0.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.director.source_2.2.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.director.source_2.2.0.dist.jar plugins/org.eclipse.equinox.p2.director.source_2.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.directorywatcher.source_1.0.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.directorywatcher.source_1.0.300.dist.jar plugins/org.eclipse.equinox.p2.directorywatcher.source_1.0.300.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.engine.source_2.2.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.engine.source_2.2.0.dist.jar plugins/org.eclipse.equinox.p2.engine.source_2.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.extensionlocation.source_1.2.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.extensionlocation.source_1.2.100.dist.jar plugins/org.eclipse.equinox.p2.extensionlocation.source_1.2.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.garbagecollector.source_1.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.garbagecollector.source_1.0.200.dist.jar plugins/org.eclipse.equinox.p2.garbagecollector.source_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.jarprocessor.source_1.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.jarprocessor.source_1.0.200.dist.jar plugins/org.eclipse.equinox.p2.jarprocessor.source_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.metadata.repository.source_1.2.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.metadata.repository.source_1.2.100.dist.jar plugins/org.eclipse.equinox.p2.metadata.repository.source_1.2.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.metadata.source_2.1.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.metadata.source_2.1.0.dist.jar plugins/org.eclipse.equinox.p2.metadata.source_2.1.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.operations.source_2.2.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.operations.source_2.2.0.dist.jar plugins/org.eclipse.equinox.p2.operations.source_2.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.publisher.eclipse.source_1.1.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.publisher.eclipse.source_1.1.0.dist.jar plugins/org.eclipse.equinox.p2.publisher.eclipse.source_1.1.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.publisher.source_1.2.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.publisher.source_1.2.0.dist.jar plugins/org.eclipse.equinox.p2.publisher.source_1.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.ql.source_2.0.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.ql.source_2.0.100.dist.jar plugins/org.eclipse.equinox.p2.ql.source_2.0.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.reconciler.dropins.source_1.1.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.reconciler.dropins.source_1.1.200.dist.jar plugins/org.eclipse.equinox.p2.reconciler.dropins.source_1.1.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.repository.source_2.2.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.repository.source_2.2.0.dist.jar plugins/org.eclipse.equinox.p2.repository.source_2.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.repository.tools.source_2.0.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.repository.tools.source_2.0.100.dist.jar plugins/org.eclipse.equinox.p2.repository.tools.source_2.0.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.touchpoint.eclipse.source_2.1.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.touchpoint.eclipse.source_2.1.100.dist.jar plugins/org.eclipse.equinox.p2.touchpoint.eclipse.source_2.1.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.touchpoint.natives.source_1.1.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.touchpoint.natives.source_1.1.0.dist.jar plugins/org.eclipse.equinox.p2.touchpoint.natives.source_1.1.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.transport.ecf.source_1.0.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.transport.ecf.source_1.0.100.dist.jar plugins/org.eclipse.equinox.p2.transport.ecf.source_1.0.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.ui.importexport.source_1.0.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.ui.importexport.source_1.0.1.dist.jar plugins/org.eclipse.equinox.p2.ui.importexport.source_1.0.1.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.ui.sdk.scheduler.source_1.1.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.ui.sdk.scheduler.source_1.1.0.dist.jar plugins/org.eclipse.equinox.p2.ui.sdk.scheduler.source_1.1.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.ui.sdk.source_1.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.ui.sdk.source_1.0.200.dist.jar plugins/org.eclipse.equinox.p2.ui.sdk.source_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.ui.source_2.2.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.ui.source_2.2.0.dist.jar plugins/org.eclipse.equinox.p2.ui.source_2.2.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.updatechecker.source_1.1.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.updatechecker.source_1.1.200.dist.jar plugins/org.eclipse.equinox.p2.updatechecker.source_1.1.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.p2.updatesite.source_1.0.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.p2.updatesite.source_1.0.400.dist.jar plugins/org.eclipse.equinox.p2.updatesite.source_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.equinox.preferences.source_3.5.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.preferences.source_3.5.0.dist.jar plugins/org.eclipse.equinox.preferences.source_3.5.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.registry.source_3.5.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.registry.source_3.5.200.dist.jar plugins/org.eclipse.equinox.registry.source_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.equinox.security.source_1.1.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.security.source_1.1.100.dist.jar plugins/org.eclipse.equinox.security.source_1.1.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.security.ui.source_1.1.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.security.ui.source_1.1.100.dist.jar plugins/org.eclipse.equinox.security.ui.source_1.1.100.dist.jar
[ ! -e plugins/org.eclipse.equinox.simpleconfigurator.manipulator.source_2.0.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.simpleconfigurator.manipulator.source_2.0.0.dist.jar plugins/org.eclipse.equinox.simpleconfigurator.manipulator.source_2.0.0.dist.jar
[ ! -e plugins/org.eclipse.equinox.simpleconfigurator.source_1.0.301.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.simpleconfigurator.source_1.0.301.dist.jar plugins/org.eclipse.equinox.simpleconfigurator.source_1.0.301.dist.jar
[ ! -e plugins/org.eclipse.equinox.util.source_1.0.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.equinox.util.source_1.0.400.dist.jar plugins/org.eclipse.equinox.util.source_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.help.appserver.source_3.1.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.help.appserver.source_3.1.400.dist.jar plugins/org.eclipse.help.appserver.source_3.1.400.dist.jar
[ ! -e plugins/org.eclipse.help.base.source_3.6.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.help.base.source_3.6.100.dist.jar plugins/org.eclipse.help.base.source_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.help.source_3.6.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.help.source_3.6.0.dist.jar plugins/org.eclipse.help.source_3.6.0.dist.jar
[ ! -e plugins/org.eclipse.help.ui.source_3.5.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.help.ui.source_3.5.200.dist.jar plugins/org.eclipse.help.ui.source_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.help.webapp.source_3.6.101.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.help.webapp.source_3.6.101.dist.jar plugins/org.eclipse.help.webapp.source_3.6.101.dist.jar
[ ! -e plugins/org.eclipse.jdt.annotation.source_1.0.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.annotation.source_1.0.0.dist.jar plugins/org.eclipse.jdt.annotation.source_1.0.0.dist.jar
[ ! -e plugins/org.eclipse.jdt.apt.core.source_3.3.500.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.apt.core.source_3.3.500.dist.jar plugins/org.eclipse.jdt.apt.core.source_3.3.500.dist.jar
[ ! -e plugins/org.eclipse.jdt.apt.pluggable.core.source_1.0.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.apt.pluggable.core.source_1.0.400.dist.jar plugins/org.eclipse.jdt.apt.pluggable.core.source_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.jdt.apt.ui.source_3.3.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.apt.ui.source_3.3.300.dist.jar plugins/org.eclipse.jdt.apt.ui.source_3.3.300.dist.jar
[ ! -e plugins/org.eclipse.jdt.compiler.apt.source_1.0.500.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.compiler.apt.source_1.0.500.dist.jar plugins/org.eclipse.jdt.compiler.apt.source_1.0.500.dist.jar
[ ! -e plugins/org.eclipse.jdt.compiler.tool.source_1.0.101.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.compiler.tool.source_1.0.101.dist.jar plugins/org.eclipse.jdt.compiler.tool.source_1.0.101.dist.jar
[ ! -e plugins/org.eclipse.jdt.core.manipulation.source_1.5.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.core.manipulation.source_1.5.0.dist.jar plugins/org.eclipse.jdt.core.manipulation.source_1.5.0.dist.jar
[ ! -e plugins/org.eclipse.jdt.core.source_3.8.2.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.core.source_3.8.2.dist.jar plugins/org.eclipse.jdt.core.source_3.8.2.dist.jar
[ ! -e plugins/org.eclipse.jdt.debug.source_3.7.101.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.debug.source_3.7.101.dist.jar plugins/org.eclipse.jdt.debug.source_3.7.101.dist.jar
[ ! -e plugins/org.eclipse.jdt.debug.ui.source_3.6.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.debug.ui.source_3.6.100.dist.jar plugins/org.eclipse.jdt.debug.ui.source_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.jdt.doc.isv_3.8.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.doc.isv_3.8.1.dist.jar plugins/org.eclipse.jdt.doc.isv_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.jdt.junit.core.source_3.7.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.junit.core.source_3.7.100.dist.jar plugins/org.eclipse.jdt.junit.core.source_3.7.100.dist.jar
[ ! -e plugins/org.eclipse.jdt.junit.runtime.source_3.4.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.junit.runtime.source_3.4.300.dist.jar plugins/org.eclipse.jdt.junit.runtime.source_3.4.300.dist.jar
[ ! -e plugins/org.eclipse.jdt.junit.source_3.7.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.junit.source_3.7.100.dist.jar plugins/org.eclipse.jdt.junit.source_3.7.100.dist.jar
[ ! -e plugins/org.eclipse.jdt.junit4.runtime.source_1.1.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.junit4.runtime.source_1.1.200.dist.jar plugins/org.eclipse.jdt.junit4.runtime.source_1.1.200.dist.jar
[ ! -e plugins/org.eclipse.jdt.launching.source_3.6.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.launching.source_3.6.100.dist.jar plugins/org.eclipse.jdt.launching.source_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.jdt.source_3.8.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.source_3.8.0.dist.jar plugins/org.eclipse.jdt.source_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.jdt.ui.source_3.8.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jdt.ui.source_3.8.1.dist.jar plugins/org.eclipse.jdt.ui.source_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.jface.databinding.source_1.6.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jface.databinding.source_1.6.0.dist.jar plugins/org.eclipse.jface.databinding.source_1.6.0.dist.jar
[ ! -e plugins/org.eclipse.jface.source_3.8.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jface.source_3.8.0.dist.jar plugins/org.eclipse.jface.source_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.jface.text.source_3.8.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jface.text.source_3.8.1.dist.jar plugins/org.eclipse.jface.text.source_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.jsch.core.source_1.1.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jsch.core.source_1.1.400.dist.jar plugins/org.eclipse.jsch.core.source_1.1.400.dist.jar
[ ! -e plugins/org.eclipse.jsch.ui.source_1.1.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.jsch.ui.source_1.1.400.dist.jar plugins/org.eclipse.jsch.ui.source_1.1.400.dist.jar
[ ! -e plugins/org.eclipse.ltk.core.refactoring.source_3.6.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ltk.core.refactoring.source_3.6.0.dist.jar plugins/org.eclipse.ltk.core.refactoring.source_3.6.0.dist.jar
[ ! -e plugins/org.eclipse.ltk.ui.refactoring.source_3.7.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ltk.ui.refactoring.source_3.7.0.dist.jar plugins/org.eclipse.ltk.ui.refactoring.source_3.7.0.dist.jar
[ ! -e plugins/org.eclipse.osgi.services.source_3.3.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.osgi.services.source_3.3.100.dist.jar plugins/org.eclipse.osgi.services.source_3.3.100.dist.jar
[ ! -e plugins/org.eclipse.osgi.source_3.8.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.osgi.source_3.8.1.dist.jar plugins/org.eclipse.osgi.source_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.osgi.util.source_3.2.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.osgi.util.source_3.2.300.dist.jar plugins/org.eclipse.osgi.util.source_3.2.300.dist.jar
[ ! -e plugins/org.eclipse.pde.api.tools.source_1.0.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.api.tools.source_1.0.400.dist.jar plugins/org.eclipse.pde.api.tools.source_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.pde.api.tools.ui.source_1.0.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.api.tools.ui.source_1.0.400.dist.jar plugins/org.eclipse.pde.api.tools.ui.source_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.pde.api.tools.ui_1.0.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.api.tools.ui_1.0.400.dist.jar plugins/org.eclipse.pde.api.tools.ui_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.pde.api.tools_1.0.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.api.tools_1.0.400.dist.jar plugins/org.eclipse.pde.api.tools_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.pde.build.source_3.8.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.build.source_3.8.1.dist.jar plugins/org.eclipse.pde.build.source_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.pde.build_3.8.1.dist ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.build_3.8.1.dist plugins/org.eclipse.pde.build_3.8.1.dist
[ ! -e plugins/org.eclipse.pde.core.source_3.8.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.core.source_3.8.0.dist.jar plugins/org.eclipse.pde.core.source_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.pde.core_3.8.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.core_3.8.0.dist.jar plugins/org.eclipse.pde.core_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.pde.doc.user_3.8.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.doc.user_3.8.1.dist.jar plugins/org.eclipse.pde.doc.user_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.pde.ds.core.source_1.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.ds.core.source_1.0.200.dist.jar plugins/org.eclipse.pde.ds.core.source_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.pde.ds.core_1.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.ds.core_1.0.200.dist.jar plugins/org.eclipse.pde.ds.core_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.pde.ds.ui.source_1.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.ds.ui.source_1.0.200.dist.jar plugins/org.eclipse.pde.ds.ui.source_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.pde.ds.ui_1.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.ds.ui_1.0.200.dist.jar plugins/org.eclipse.pde.ds.ui_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.pde.junit.runtime.source_3.4.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.junit.runtime.source_3.4.200.dist.jar plugins/org.eclipse.pde.junit.runtime.source_3.4.200.dist.jar
[ ! -e plugins/org.eclipse.pde.junit.runtime_3.4.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.junit.runtime_3.4.200.dist.jar plugins/org.eclipse.pde.junit.runtime_3.4.200.dist.jar
[ ! -e plugins/org.eclipse.pde.launching.source_3.6.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.launching.source_3.6.100.dist.jar plugins/org.eclipse.pde.launching.source_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.pde.launching_3.6.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.launching_3.6.100.dist.jar plugins/org.eclipse.pde.launching_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.pde.runtime.source_3.4.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.runtime.source_3.4.300.dist.jar plugins/org.eclipse.pde.runtime.source_3.4.300.dist.jar
[ ! -e plugins/org.eclipse.pde.runtime_3.4.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.runtime_3.4.300.dist.jar plugins/org.eclipse.pde.runtime_3.4.300.dist.jar
[ ! -e plugins/org.eclipse.pde.source_3.7.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.source_3.7.0.dist.jar plugins/org.eclipse.pde.source_3.7.0.dist.jar
[ ! -e plugins/org.eclipse.pde.ua.core.source_1.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.ua.core.source_1.0.200.dist.jar plugins/org.eclipse.pde.ua.core.source_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.pde.ua.core_1.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.ua.core_1.0.200.dist.jar plugins/org.eclipse.pde.ua.core_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.pde.ua.ui.source_1.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.ua.ui.source_1.0.200.dist.jar plugins/org.eclipse.pde.ua.ui.source_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.pde.ua.ui_1.0.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.ua.ui_1.0.200.dist.jar plugins/org.eclipse.pde.ua.ui_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.pde.ui.source_3.7.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.ui.source_3.7.1.dist.jar plugins/org.eclipse.pde.ui.source_3.7.1.dist.jar
[ ! -e plugins/org.eclipse.pde.ui.templates.source_3.4.500.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.ui.templates.source_3.4.500.dist.jar plugins/org.eclipse.pde.ui.templates.source_3.4.500.dist.jar
[ ! -e plugins/org.eclipse.pde.ui.templates_3.4.500.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.ui.templates_3.4.500.dist.jar plugins/org.eclipse.pde.ui.templates_3.4.500.dist.jar
[ ! -e plugins/org.eclipse.pde.ui_3.7.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde.ui_3.7.1.dist.jar plugins/org.eclipse.pde.ui_3.7.1.dist.jar
[ ! -e plugins/org.eclipse.pde_3.7.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.pde_3.7.0.dist.jar plugins/org.eclipse.pde_3.7.0.dist.jar
[ ! -e plugins/org.eclipse.platform.doc.isv_3.8.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.platform.doc.isv_3.8.1.dist.jar plugins/org.eclipse.platform.doc.isv_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.platform.source_3.8.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.platform.source_3.8.1.dist.jar plugins/org.eclipse.platform.source_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.rcp.source_3.8.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.rcp.source_3.8.0.dist.jar plugins/org.eclipse.rcp.source_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.sdk_3.8.1.dist ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.sdk_3.8.1.dist plugins/org.eclipse.sdk_3.8.1.dist
[ ! -e plugins/org.eclipse.search.source_3.8.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.search.source_3.8.0.dist.jar plugins/org.eclipse.search.source_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.team.core.source_3.6.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.team.core.source_3.6.100.dist.jar plugins/org.eclipse.team.core.source_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.team.cvs.core.source_3.3.500.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.team.cvs.core.source_3.3.500.dist.jar plugins/org.eclipse.team.cvs.core.source_3.3.500.dist.jar
[ ! -e plugins/org.eclipse.team.cvs.ssh2.source_3.2.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.team.cvs.ssh2.source_3.2.300.dist.jar plugins/org.eclipse.team.cvs.ssh2.source_3.2.300.dist.jar
[ ! -e plugins/org.eclipse.team.cvs.ui.source_3.3.500.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.team.cvs.ui.source_3.3.500.dist.jar plugins/org.eclipse.team.cvs.ui.source_3.3.500.dist.jar
[ ! -e plugins/org.eclipse.team.ui.source_3.6.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.team.ui.source_3.6.200.dist.jar plugins/org.eclipse.team.ui.source_3.6.200.dist.jar
[ ! -e plugins/org.eclipse.text.source_3.5.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.text.source_3.5.200.dist.jar plugins/org.eclipse.text.source_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.ui.browser.source_3.4.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.browser.source_3.4.1.dist.jar plugins/org.eclipse.ui.browser.source_3.4.1.dist.jar
[ ! -e plugins/org.eclipse.ui.cheatsheets.source_3.4.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.cheatsheets.source_3.4.200.dist.jar plugins/org.eclipse.ui.cheatsheets.source_3.4.200.dist.jar
[ ! -e plugins/org.eclipse.ui.console.source_3.5.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.console.source_3.5.100.dist.jar plugins/org.eclipse.ui.console.source_3.5.100.dist.jar
[ ! -e plugins/org.eclipse.ui.editors.source_3.8.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.editors.source_3.8.0.dist.jar plugins/org.eclipse.ui.editors.source_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.ui.externaltools.source_3.2.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.externaltools.source_3.2.100.dist.jar plugins/org.eclipse.ui.externaltools.source_3.2.100.dist.jar
[ ! -e plugins/org.eclipse.ui.forms.source_3.5.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.forms.source_3.5.200.dist.jar plugins/org.eclipse.ui.forms.source_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.ui.ide.application.source_1.0.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.ide.application.source_1.0.400.dist.jar plugins/org.eclipse.ui.ide.application.source_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.ui.ide.source_3.8.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.ide.source_3.8.1.dist.jar plugins/org.eclipse.ui.ide.source_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.ui.intro.source_3.4.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.intro.source_3.4.200.dist.jar plugins/org.eclipse.ui.intro.source_3.4.200.dist.jar
[ ! -e plugins/org.eclipse.ui.intro.universal.source_3.2.600.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.intro.universal.source_3.2.600.dist.jar plugins/org.eclipse.ui.intro.universal.source_3.2.600.dist.jar
[ ! -e plugins/org.eclipse.ui.navigator.resources.source_3.4.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.navigator.resources.source_3.4.400.dist.jar plugins/org.eclipse.ui.navigator.resources.source_3.4.400.dist.jar
[ ! -e plugins/org.eclipse.ui.navigator.source_3.5.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.navigator.source_3.5.200.dist.jar plugins/org.eclipse.ui.navigator.source_3.5.200.dist.jar
[ ! -e plugins/org.eclipse.ui.net.source_1.2.101.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.net.source_1.2.101.dist.jar plugins/org.eclipse.ui.net.source_1.2.101.dist.jar
[ ! -e plugins/org.eclipse.ui.presentations.r21.source_3.2.201.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.presentations.r21.source_3.2.201.dist.jar plugins/org.eclipse.ui.presentations.r21.source_3.2.201.dist.jar
[ ! -e plugins/org.eclipse.ui.source_3.8.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.source_3.8.0.dist.jar plugins/org.eclipse.ui.source_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.ui.trace.source_1.0.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.trace.source_1.0.1.dist.jar plugins/org.eclipse.ui.trace.source_1.0.1.dist.jar
[ ! -e plugins/org.eclipse.ui.trace_1.0.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.trace_1.0.1.dist.jar plugins/org.eclipse.ui.trace_1.0.1.dist.jar
[ ! -e plugins/org.eclipse.ui.views.log.source_1.0.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.views.log.source_1.0.300.dist.jar plugins/org.eclipse.ui.views.log.source_1.0.300.dist.jar
[ ! -e plugins/org.eclipse.ui.views.log_1.0.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.views.log_1.0.300.dist.jar plugins/org.eclipse.ui.views.log_1.0.300.dist.jar
[ ! -e plugins/org.eclipse.ui.views.properties.tabbed.source_3.5.300.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.views.properties.tabbed.source_3.5.300.dist.jar plugins/org.eclipse.ui.views.properties.tabbed.source_3.5.300.dist.jar
[ ! -e plugins/org.eclipse.ui.views.source_3.6.100.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.views.source_3.6.100.dist.jar plugins/org.eclipse.ui.views.source_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.ui.workbench.compatibility.source_3.2.101.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.workbench.compatibility.source_3.2.101.dist.jar plugins/org.eclipse.ui.workbench.compatibility.source_3.2.101.dist.jar
[ ! -e plugins/org.eclipse.ui.workbench.source_3.8.1.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.workbench.source_3.8.1.dist.jar plugins/org.eclipse.ui.workbench.source_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.ui.workbench.texteditor.source_3.8.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.ui.workbench.texteditor.source_3.8.0.dist.jar plugins/org.eclipse.ui.workbench.texteditor.source_3.8.0.dist.jar
[ ! -e plugins/org.eclipse.update.configurator.source_3.3.200.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.update.configurator.source_3.3.200.dist.jar plugins/org.eclipse.update.configurator.source_3.3.200.dist.jar
[ ! -e plugins/org.eclipse.update.core.source_3.2.600.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.update.core.source_3.2.600.dist.jar plugins/org.eclipse.update.core.source_3.2.600.dist.jar
[ ! -e plugins/org.eclipse.update.scheduler.source_3.2.400.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.update.scheduler.source_3.2.400.dist.jar plugins/org.eclipse.update.scheduler.source_3.2.400.dist.jar
[ ! -e plugins/org.eclipse.update.ui.source_3.3.0.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.eclipse.update.ui.source_3.3.0.dist.jar plugins/org.eclipse.update.ui.source_3.3.0.dist.jar
[ ! -e plugins/org.junit.source_3.8.2.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.junit.source_3.8.2.dist.jar plugins/org.junit.source_3.8.2.dist.jar
[ ! -e plugins/org.junit.source_4.8.2.dist.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.junit.source_4.8.2.dist.jar plugins/org.junit.source_4.8.2.dist.jar
[ ! -e plugins/org.objectweb.asm_3.3.2.jar ] && ln -s $eclipse/dropins/sdk/plugins/org.objectweb.asm_3.3.2.jar plugins/org.objectweb.asm_3.3.2.jar
[ ! -e plugins/junit4.jar ] && ln -s $datadir/dropins/jdt/plugins/junit4.jar plugins/junit4.jar
[ ! -e plugins/org.eclipse.ant.launching_1.0.200.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.ant.launching_1.0.200.dist.jar plugins/org.eclipse.ant.launching_1.0.200.dist.jar
[ ! -e plugins/org.eclipse.ant.ui_3.5.300.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.ant.ui_3.5.300.dist.jar plugins/org.eclipse.ant.ui_3.5.300.dist.jar
[ ! -e plugins/org.eclipse.jdt.annotation_1.0.0.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.annotation_1.0.0.dist.jar plugins/org.eclipse.jdt.annotation_1.0.0.dist.jar
[ ! -e plugins/org.eclipse.jdt.apt.core_3.3.500.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.apt.core_3.3.500.dist.jar plugins/org.eclipse.jdt.apt.core_3.3.500.dist.jar
[ ! -e plugins/org.eclipse.jdt.apt.pluggable.core_1.0.400.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.apt.pluggable.core_1.0.400.dist.jar plugins/org.eclipse.jdt.apt.pluggable.core_1.0.400.dist.jar
[ ! -e plugins/org.eclipse.jdt.apt.ui_3.3.300.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.apt.ui_3.3.300.dist.jar plugins/org.eclipse.jdt.apt.ui_3.3.300.dist.jar
[ ! -e plugins/org.eclipse.jdt.compiler.apt_1.0.500.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.compiler.apt_1.0.500.dist.jar plugins/org.eclipse.jdt.compiler.apt_1.0.500.dist.jar
[ ! -e plugins/org.eclipse.jdt.compiler.tool_1.0.101.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.compiler.tool_1.0.101.dist.jar plugins/org.eclipse.jdt.compiler.tool_1.0.101.dist.jar
[ ! -e plugins/org.eclipse.jdt.core.manipulation_1.5.0.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.core.manipulation_1.5.0.dist.jar plugins/org.eclipse.jdt.core.manipulation_1.5.0.dist.jar
[ ! -e plugins/org.eclipse.jdt.debug.ui_3.6.100.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.debug.ui_3.6.100.dist.jar plugins/org.eclipse.jdt.debug.ui_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.jdt.debug_3.7.101.dist ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.debug_3.7.101.dist plugins/org.eclipse.jdt.debug_3.7.101.dist
[ ! -e plugins/org.eclipse.jdt.doc.user_3.8.1.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.doc.user_3.8.1.dist.jar plugins/org.eclipse.jdt.doc.user_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.jdt.junit.core_3.7.100.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.junit.core_3.7.100.dist.jar plugins/org.eclipse.jdt.junit.core_3.7.100.dist.jar
[ ! -e plugins/org.eclipse.jdt.junit.runtime_3.4.300.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.junit.runtime_3.4.300.dist.jar plugins/org.eclipse.jdt.junit.runtime_3.4.300.dist.jar
[ ! -e plugins/org.eclipse.jdt.junit4.runtime_1.1.200.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.junit4.runtime_1.1.200.dist.jar plugins/org.eclipse.jdt.junit4.runtime_1.1.200.dist.jar
[ ! -e plugins/org.eclipse.jdt.junit_3.7.100.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.junit_3.7.100.dist.jar plugins/org.eclipse.jdt.junit_3.7.100.dist.jar
[ ! -e plugins/org.eclipse.jdt.launching_3.6.100.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.launching_3.6.100.dist.jar plugins/org.eclipse.jdt.launching_3.6.100.dist.jar
[ ! -e plugins/org.eclipse.jdt.ui_3.8.1.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt.ui_3.8.1.dist.jar plugins/org.eclipse.jdt.ui_3.8.1.dist.jar
[ ! -e plugins/org.eclipse.jdt_3.8.0.dist.jar ] && ln -s $datadir/dropins/jdt/plugins/org.eclipse.jdt_3.8.0.dist.jar plugins/org.eclipse.jdt_3.8.0.dist.jar
[ ! -e plugins/org.hamcrest.core_1.3.0.jar ] && ln -s $datadir/dropins/jdt/plugins/org.hamcrest.core_1.3.0.jar plugins/org.hamcrest.core_1.3.0.jar
[ ! -e plugins/org.junit4 ] && ln -s $datadir/dropins/jdt/plugins/org.junit4 plugins/org.junit4
[ ! -e plugins/org.junit4_4.8.1.dist ] && ln -s $datadir/dropins/jdt/plugins/org.junit4_4.8.1.dist plugins/org.junit4_4.8.1.dist
[ ! -e plugins/org.junit_3.8.2.dist ] && ln -s $datadir/dropins/jdt/plugins/org.junit_3.8.2.dist plugins/org.junit_3.8.2.dist
[ ! -e plugins/org.junit_3.8.2.v3_8_2_v20100427-1100 ] && ln -s $datadir/dropins/jdt/plugins/org.junit_3.8.2.v3_8_2_v20100427-1100 plugins/org.junit_3.8.2.v3_8_2_v20100427-1100
[ ! -e plugins/org.junit_4.8.2.dist ] && ln -s $datadir/dropins/jdt/plugins/org.junit_4.8.2.dist plugins/org.junit_4.8.2.dist
[ ! -e plugins/org.junit_4.8.2.v4_8_2_v20110321-1705 ] && ln -s $datadir/dropins/jdt/plugins/org.junit_4.8.2.v4_8_2_v20110321-1705 plugins/org.junit_4.8.2.v4_8_2_v20110321-1705
