/* generated by dia/codegen.py */
class Levrier : Chien 
{
public:
	void cri ();
protected:
	Nourriture nourritureFavorite;
};

class Chien 
{
public:
	void cri ();
	boolean estCarnivore ();
	String nom;
protected:
	int age;
private:
	String tatouage_;
};

class Nourriture 
{
public:
	String nom;
	int valeurCalorique;
};

/*(NULL)*/
class Animal 
{
public:
	void cri ();
	boolean estCarnivore ();
};

class Lapin 
{
public:
	void cri ();
	boolean estCarnivore ();
	void combienDeCarottes (int carottes);
private:
	double taille_;
};

