/* generated by dia/codegen.py */
/*(NULL)*/
class Sha256 
{
public:
	voidString crypter (String crypter);
};

/*(NULL)*/
class Md5 
{
public:
	voidString crypter (String crypter);
};

/*(NULL)*/
class Donnees 
{
public:
	void affichage ();
	void crypter ();
protected:
	String data;
	StrategyCryp cryptageType;
};

/*(NULL)*/
class Sha512 
{
public:
	voidString crypter (String crypter);
};

/*(NULL)*/
class StrategyCryp 
{
public:
	String crypter (String data);
};

